name: Build and publish Dockerimage for rails to AWS ECR

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      RAILS_MASTER_KEY:
        required: true
    outputs:
      IMAGE:
        description: "Full name of the repository image"
        value: ${{ jobs.build-and-push.outputs.IMAGE }}
      IMAGE_TAG:
        description: "Tag of the repository image"
        value: ${{ jobs.build-and-push.outputs.IMAGE_TAG }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      IMAGE: ${{ steps.build.outputs.IMAGE }}
      IMAGE_TAG: ${{ steps.build.outputs.IMAGE_TAG }}
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}
          mask-aws-account-id: 'no'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Build, tag, and push to repository
        id: build
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
          IMAGE_TAG: ${{ github.sha }}
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          docker build -f Dockerfile --build-arg RAILS_MASTER_KEY=$RAILS_MASTER_KEY --platform linux/x86_64 -t $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
          echo "IMAGE=$ECR_REGISTRY/$IMAGE_NAME:$IMAGE_TAG" >> "$GITHUB_OUTPUT"
          echo "IMAGE_TAG=$IMAGE_TAG" >> "$GITHUB_OUTPUT"
