name: Deploy an ECR image to ECS with a CDK stack

on:
  workflow_call:
    inputs:
      AWS_REGION:
        required: true
        type: string
      STACK_NAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

jobs:
  aws_cdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: cdk/package-lock.json

      - name: Install dependencies
        working-directory: ./cdk
        run: npm install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ inputs.AWS_REGION }}

      - name: cdk deploy
        working-directory: ./cdk
        run: npx cdk deploy ${{ inputs.STACK_NAME }} --profile "" --require-approval never --ci -c ecr-image=${{ inputs.IMAGE_NAME }}
