name: Download an image from Dockerhub and save as artifact

on:
  workflow_call:
    inputs:
      DOCKERHUB_USERNAME:
        required: true
        type: string
      IMAGE_NAME:
        required: true
        type: string
      IMAGE_TAG:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      AWS_ECR:
        required: true
        type: string

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download, tag, and push to repository
        id: download
        env:
          IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
          IMAGE_TAG: ${{ inputs.IMAGE_TAG }}
          DOCKERHUB_USERNAME: ${{ inputs.DOCKERHUB_USERNAME }}
        run: |
          docker pull $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
          docker image tag $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:$IMAGE_TAG
          docker save --output /tmp/${IMAGE_NAME}.tar ${IMAGE_NAME}:${IMAGE_TAG}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.IMAGE_NAME }}-${{ github.sha  }}
          path: /tmp/${{ inputs.IMAGE_NAME }}.tar
          retention-days: 1

  push-to-ecr:
    needs: [download]
    uses: nasmorn/actions/.github/workflows/ecr-push.yml@main
    with:
      AWS_REGION: ${{ inputs.AWS_REGION }}
      IMAGE_NAME: ${{ inputs.IMAGE_NAME }}
    secrets: inherit
    permissions:
      contents: read
